From ubuntu:latest

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Instala as dependências
RUN apt update && apt install iputils-ping net-tools python3 python3-pip -y

# Copia o restante do código da aplicação
COPY src/servidor_assincrono/servidorAssincrono.py ./src/

EXPOSE 80

# Comando para iniciar a aplicação cliente
CMD ["python3", "servidorAssincrono.py"]