FROM ubuntu:latest

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Instala as dependências
RUN apt update && apt install iputils-ping net-tools python3 python3-pip -y

# Copia o restante do código da aplicação
COPY servidorAssincrono.py ./src/

EXPOSE 8080

# Comando para iniciar a aplicação cliente
CMD ["python3", "/app/src/servidorAssincrono.py"]