services:
  servidor-sincrono:
    build: ./servidor_sincrono
    container_name: servidor-sincrono
    networks:
      redes:
        ipv4_address: 95.58.0.2
    ports:
      - "8080:80"

  server-async:
    build: ./servidor_assincrono
    container_name: servidor-assincrono
    networks:
      redes:
        ipv4_address: 95.58.0.3
    ports:
      - "8000:80"

  client:
    build: ./cliente
    container_name: cliente
    depends_on:
      - servidor_sincrono
      - servidor-assincrono
    networks:
      redes:
        ipv4_address: 95.58.0.4

networks:
  redes:
    driver: bridge
    ipam:
      config:
        - subnet: 95.58.0.0/24