FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && apt-get install -y \
    iputils-ping \
    net-tools \
    python3 \
    python3-pip \
    python3-matplotlib \
    python3-numpy \
    python3-pandas \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

CMD bash -c "python3 cliente.py && python3 testes.py && python3 resultados.py"