FROM ubuntu:latest


# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Instala as dependências
RUN apt update && apt install iputils-ping net-tools python3 python3-pip -y

# Copia o restante do código da aplicação
COPY . /app

# Comando para rodar o cliente e, em seguida, gerar os resultados
CMD bash -c "python3 cliente.py && python3 testes.py && python3 resultados.py" 
#visualizar_resultados.py

# # Comando para iniciar a aplicação cliente
# CMD ["python3", "cliente.py"]